# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A CLI to get weather forecasts."
  homepage "https://github.com/cybo42/weather-cli2"
  version "1.2.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.9/weather-cli_darwin_amd64.tar.gz"
      sha256 "a95a003f6f45d72a65ac86054a176b422eeb6a145a79f0b3157b491524786b8e"

      def install
        bin.install "weather-cli"
      end
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.9/weather-cli_darwin_arm64.tar.gz"
      sha256 "2ca4ab29110dd0e5d499ac8a83de70142d6eae44024327cf394bb60406b5aa64"

      def install
        bin.install "weather-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.9/weather-cli_linux_amd64.tar.gz"
        sha256 "573d84e0742653c6d92f4a4d9ea2a8a86995c7ec76a19e9cb84dc69c3a6b8be6"

        def install
          bin.install "weather-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.9/weather-cli_linux_arm64.tar.gz"
        sha256 "c8ea4034964e8161b2fde104a5836e58d28d73d71203e6563982f04f5a530eaf"

        def install
          bin.install "weather-cli"
        end
      end
    end
  end
end
