# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A CLI to get weather forecasts."
  homepage "https://github.com/cybo42/weather-cli2"
  version "1.2.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.11/weather-cli_darwin_amd64.tar.gz"
      sha256 "7ae6d8839622bc3f78823250738e990871b742d57cec97e42e59a8d01b233535"

      def install
        bin.install "weather-cli"
      end
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.11/weather-cli_darwin_arm64.tar.gz"
      sha256 "e57c3e107442d12f078c4a49e1ac79bd08b8fb4158e542bb8f47317f0cef2d45"

      def install
        bin.install "weather-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.11/weather-cli_linux_amd64.tar.gz"
        sha256 "84dcdcde9d49a20cf430b97b16cb9ede99180510ae3047cf04eda3ab7299e7a3"

        def install
          bin.install "weather-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.11/weather-cli_linux_arm64.tar.gz"
        sha256 "c8b3e9ddbb683abf724f9e5a246e69de775f5cd1d76ed684727db33eb0a7e3d0"

        def install
          bin.install "weather-cli"
        end
      end
    end
  end
end
