# This file was generated by GoReleaser. DO NOT EDIT.
cask "pretty-zerolog" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "92bd3492714c5608309f412f7e269fe64eb8b5613bcc110790c29b4e9a5698d6"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "731b2e609a60999e058196c83c9d3c56973d7fd13d8f657435fc5f15fbf71180"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19407431cfc32220cb51922ce024066f6734450a485b923a45a222d1ed88ab47"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eccbb6da3876ad3b9805a3aadffa5fd32967654e0d857ff876dab8c315debd3f"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pretty-zerolog"
  desc "Pretty-print zerolog JSON output"
  homepage "https://github.com/cybo42/pretty-zerolog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pretty-zerolog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pretty-zerolog"]
    end
  end

  # No zap stanza required

end
