# This file was generated by GoReleaser. DO NOT EDIT.
cask "pretty-zerolog" do
  version "1.2.4"

  on_macos do
    on_intel do
      sha256 "706c8f46fb3bb4a5dccd1355c6c3e9d6e0245361b51758dc494aa3483fa530bb"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "520e16f44d6199f665d9a348a3b3dee352bacc268f3a31948bfb0fac068bc29c"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d16b47a875edffa158ebe8da7c1a8c23a6952776d7b3d57e0e398d15b5f76c3b"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1853911c9925bf8aacb2751b27d763db7bbdc4f34cf5619479493d776b308a71"
      url "https://github.com/cybo42/pretty-zerolog/releases/download/v#{version}/pretty-zerolog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pretty-zerolog"
  desc "Pretty-print zerolog JSON output"
  homepage "https://github.com/cybo42/pretty-zerolog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pretty-zerolog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pretty-zerolog"]
    end
  end

  # No zap stanza required

end
