# This file was generated by GoReleaser. DO NOT EDIT.
cask "weather-cli" do
  name "weather-cli"
  desc "A CLI to get weather forecasts."
  homepage "https://github.com/cybo42/weather-cli2"
  version "1.2.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weather-cli"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_darwin_amd64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "10136050c0f6b38afeaf1bc00ff229c914a4a6e3b6e4e0deeedc3a7a21c00ffa"
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_darwin_arm64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "6fcc894cbb342b9cd5654252235bda475133f5a6657d7fc650b23f6e43f43d0d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_linux_amd64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "9460ce1fb4c986c7fe522e7aafe85d3fb5ea749658bc061bd3ef9b7016e6382a"
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_linux_arm64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "e3c59694fcb010475d7dd2a8a50895631f375244c17136e5d0c36e6a586d4819"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/weather-cli"]
    end
  end

  # No zap stanza required
end
