# This file was generated by GoReleaser. DO NOT EDIT.
cask "weather-cli" do
  name "weather-cli"
  desc "A CLI to get weather forecasts."
  homepage "https://github.com/cybo42/weather-cli2"
  version "1.2.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weather-cli"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_darwin_amd64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "502bb6cd85c44490c84b7c0aa4b8e9a9c5ce5e35c32afc59deb798512631d0f2"
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_darwin_arm64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "b58efdad15fb7fb28b11a4065ca148b94286889319ab563011230064cba8ce15"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_linux_amd64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "81959414412c775ee92e448d233cdc3b11a60066cdee4211b77f95ae10196b8c"
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_linux_arm64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "879ffbfb2fe133f12511b6903d6a6d1518f1cabf351a034e36872d12e09f84a0"
    end
  end

  # No zap stanza required
end
