# This file was generated by GoReleaser. DO NOT EDIT.
cask "weather-cli" do
  name "weather-cli"
  desc "A CLI to get weather forecasts."
  homepage "https://github.com/cybo42/weather-cli2"
  version "1.2.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weather-cli"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_darwin_amd64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "9eb2914eb571f8a546a6545ff6ea8dcb9e0e0746c8ea1e5f16d4c9d20a362972"
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_darwin_arm64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "1424c05da36d70ede1266063177cc7c604e2116d1634a214820c0f21a751e73a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_linux_amd64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "09387750eeb712accfc0c0fe14353dc5a333c950e9eea2c181e3dd5c0f5957d2"
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v#{version}/weather-cli_linux_arm64.tar.gz",
        verified: "github.com/cybo42/weather-cli2/"
      sha256 "79b72e1288cf9b3ae61288c8c2c2ba975bd11993d51099287c47b4101035990a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
