class TmuxUtils < Formula
  desc "A collection of tmux utilities"
  homepage "https://github.com/cybo42/tmux-utils"
  url "https://github.com/cybo42/tmux-utils/archive/refs/tags/v0.0.5.tar.gz"
  sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
  version "0.0.5"

  def install
    bin.install "tmu2"
    bin.install "tmux-window-pwd"
  end
end

# typed: false
# frozen_string_literal: true

# This file is generated by a CI script
# For more information, see: https://github.com/cybo42/tmux-utils/blob/main/.github/workflows/publish_homebrew.yml
class PrivateRepoDownloadStrategy < CurlDownloadStrategy
  require "utils/formatter"
  require "utils/github"

  def initialize(url, name, version, **meta)
    super
    parse_url_pattern
    set_github_token
  end

  def parse_url_pattern
    unless match = url.match(%r{https://github.com/([^/]+)/([^/]+)/archive/v?(\d+\.\d+\.\d+)\.tar\.gz})
      raise CurlDownloadStrategyError, "Invalid URL pattern for GitHub Repository."
    end

    _, @owner, @repo, @version = *match
  end

  def download_url
    "https://api.github.com/repos/#{@owner}/#{@repo}/tarball/v#{@version}"
  end

  private

  def _fetch(url:, resolved_url:, timeout:)
    # HTTP request header `Accept: application/octet-stream` is required.
    # Without this, the GitHub API will respond with a 302 Found redirect to the actual file.
    curl_download download_url, "--header", "Accept: application/octet-stream", "--header", "Authorization: token #{@github_token}"
  end

  def set_github_token
    @github_token = ENV["PAT"]
    unless @github_token
      raise CurlDownloadStrategyError, "Environmental variable HOMEBREW_GITHUB_API_TOKEN is required."
    end

    validate_github_token
  end

  def validate_github_token
    scopes = GitHub.api_credentials_type(@github_token)
    return if scopes.include? "repo"
    return if scopes.include? "public_repo"

    raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN requires repo or public_repo scope."
  end
end
