# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A simple CLI application that prints hello world"
  homepage "https://github.com/cybo42/weather-cli"
  version "1.2.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.8/weather-cli2_Darwin_x86_64.tar.gz"
      sha256 "b41b183cf1706d65e9c6d6fa65505633a8193765a007c3a5e222be12f14c0f00"

      def install
        bin.install "weather-cli"
      end
    end
    on_arm do
      url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.8/weather-cli2_Darwin_arm64.tar.gz"
      sha256 "9ce2a440d776dcf1f1c3b139f2f979d7539c56f83c60481c0edd16083c0c4c9a"

      def install
        bin.install "weather-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.8/weather-cli2_Linux_x86_64.tar.gz"
        sha256 "e1c365834501431566935b881f82f806ab749d46ea8df637d794f6efc283a4ae"

        def install
          bin.install "weather-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cybo42/weather-cli2/releases/download/v1.2.8/weather-cli2_Linux_arm64.tar.gz"
        sha256 "318434dd64fdb858cf5c4f8aa23cddd99964e3b9f58b5dc84080ca64440ea149"

        def install
          bin.install "weather-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/weather-cli --version"
  end
end
